### ISSUE TITLE
Problems on example codes

### ISSUE THREAD

**Issue by JaeHyung-Kim** [MiZhenxing/Switch-NeRF#5]
Hello! 
Thank you for sharing your code.
I am trying to reproduce your result on Mega-NeRF building dataset.
I am using one RTX A6000 GPU.
During generating chunks, I have an error.

```
Traceback (most recent call last):
  File "/home/user/anaconda3/envs/nerf/lib/python3.8/runpy.py", line 194, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/home/user/anaconda3/envs/nerf/lib/python3.8/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/user/switchnerf/Switch-NeRF/switch_nerf/train.py", line 28, in <module>
    main(_get_train_opts())
  File "/home/user/anaconda3/envs/nerf/lib/python3.8/site-packages/torch/distributed/elastic/multiprocessing/errors/__init__.py", line 345, in wrapper
    return f(*args, **kwargs)
  File "/home/user/switchnerf/Switch-NeRF/switch_nerf/train.py", line 24, in main
    Runner(hparams).train()
  File "/home/user/switchnerf/Switch-NeRF/switch_nerf/runner.py", line 532, in train
    dataset = FilesystemDataset(self.train_items, self.near, self.far, self.ray_altitude_range,
  File "/home/user/switchnerf/Switch-NeRF/switch_nerf/datasets/filesystem_dataset.py", line 55, in __init__
    append_arrays = self._check_existing_paths(chunk_paths, center_pixels, scale_factor,
  File "/home/user/switchnerf/Switch-NeRF/switch_nerf/datasets/filesystem_dataset.py", line 296, in _check_existing_paths
    assert (chunk_path / 'metadata.pt').exists(), \
AssertionError: Could not find metadata file (did previous writing to this directory not complete successfully?)
```

where can I generate metadata.pt? 

I thought that the example script generates the data chunk, but somehow it requires me to give it metadata of the data chunk.

I am trying to run Mega-NeRF too, but it is hard to find.

Please let me know if you have any solution.

Also, in the bungee-nerf training code, 

```
CUDA_VISIBLE_DEVICES=0 python -m torch.distributed.launch --use_env --master_port=12345 --nproc_per_node=1 -m mega_nerf.train_nerf_moe --config=switch_nerf/configs/switch_nerf/bungee.yaml
```
So there comes "mega_nerf.train_nerf_moe FAILED" error.

I guess it should be changed to "switch_nerf.train_nerf_moe" ! and it works well.

Thank you!

**Comment by MiZhenxing** [comment]
Hi, sorry for the late response. Before training the models, we need to generate data chunks. The file 'metadata.pt' is created after all the chunks are successfully generated. When you rerun the code, it automatically checks whether the chunk_paths exist. If it exists, it will reuse the chunks in the path without re-generating them. So if in previous runs, the chunks were not successfully generated, the code will try to re-use the chunks but find no necessary files. So it will crash. To solve this, you can just delete the unsuccessful chunk_paths and re-generate the data chunks by the command line provided [here](https://github.com/MiZhenxing/Switch-NeRF/blob/fe3d30bc7f59d80692cd20520dd5170a977df608/README.md?plain=1#L44) in the readme file.

**Comment by YHJCTR** [comment]
Hi! When I delete the directories for exp and chunks, the code creates them automatically and runs successfully
